# Generated by Django 2.2.6 on 2019-10-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
